### ISSUE TITLE
North Antelope Rochelle Mine Test

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/mtm#115]
We want to explore adapting the surface mine identification process to other geographic areas, specifically the Powder River Basin (PRB). We will start by adapting the process to focus on one mine in the PRB, the North Antelope Rochelle Mine.

Brady will be adapting the MTR EE scripts to look at this mine, as well as creating a new mask to be used in the analysis process. He will be meticulously documenting his steps, and noting any issues he encounters. 

## Tasks
- [x] create a mask (for roads, rivers, urban areas) for the area around the North Antelope Rochelle Mine
- [x] adapt the greenestCompositesToAssets.js script
- [x] adapt the annualThresholdImages.js script
- [x] adapt the annualMiningArea.js script
